enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[GooglePhotos]
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
exclusive-patches = true
included-patches = """\
  'Spoof features' \
  'Enable DCIM folders backup control' \
  'GmsCore support' \
  'Change package name' \
  """
arch = "both"